```{python echo=FALSE}
import warnings
import pandas as pd
import numpy as np
import python.api_calls as api
import python.connectivity_assess as conn_table

warnings.filterwarnings('ignore')


```

```{r echo=FALSE}
#| echo: false
#| include: true
#| warning: false

library(reticulate)

```

# Connectivity Status and Ranking

## Current Connectivity Status {.unnumbered}

The current connectivity status assessment relies on GIS analyses to map known and modelled barriers to fish passage, identify stream reaches that have potential spawning and rearing habitat, estimate the proportion of habitat that is currently accessible to target species, and prioritize barriers for field assessment that would provide the greatest gains in connectivity. To support a flexible prioritization framework to identify priority barriers in the watershed, two assumptions are made: 1,any modelled (i.e., passability status is unknown) or partial barriers are treated as complete barriers to passage and 2, the habitat modelling is binary, it does not assign any habitat quality values. As such, the current connectivity status will be refined over time as more data on habitat and barriers are collected. For more detail on how the connectivity status assessments were conducted, see Data Download and Methods.

```{python echo=FALSE}
#| label: tbl-connectivity
#| tbl-cap: "Table showing current connectivity status for the Margaree watershed and the percentage of connected versus disconnected key habitat within the watershed as of February 27th, 2026."
#| warning: false
#| echo: false

df = conn_table.make_assess_table("Atlantic Salmon", "% of Key Habitat", "% of total habitat", 50, 75, 90, api.connect)
df

```

**Comments:** Indicator rating definitions are based on the consensus decisions of the planning team, including the decision not to define Fair. The current status is based on the connectivity model output, which is current as of February 5th, 2026.

Ranking of structures helps to identify which structures would open up the most habitat in key habitat areas of the watershed, this acts as a planning tool to indicate which barriers make sense to focus on in order to have the most impact on connectivity for focal species in the watershed. 

```{python echo=FALSE}
#| label: tbl-goals
#| tbl-cap: "Goals to improve (1) spawning, and (2) rearing habitat connectivity for focal species in the Margaree watershed over the lifespan of the WCRP (2024-2035). The goals were established through discussions with the planning team and represent the resulting desired state of connectivity in the watershed. The goals are subject to change as more information and data are collected over the course of the plan timeline (e.g., the current connectivity status is updated based on barrier field assessments)."
#| warning: false
#| echo: false
df = pd.DataFrame({"Goal #": [1],
                   "Goal": ["By 2035, increase the amount of connected habitat within the Margaree watershed."]
                    })

data = df.style.hide().set_properties(**{'text-align': 'left'})

data.set_table_styles(
   [{
       'selector': 'th',
       'props': [('background-color', '#008270'),('text-align', 'left')]
   }])

```

## Habitat Accumulation Curve {.unnumbered}

![Habitat Accumulation Curve (HAC) showing structures in the Margaree watershed as of February 5th, 2026. Structures are ranked based on how much (km) habitat is upstream to the next structure or set of structures and that would be reconnected if the structure(s) became passable. Habitat upstream of data-deficient structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown; however, rehabilitated barriers are shown to demonstrate the connectivity gains achieved through implementation of this plan.](content/images/HAC-marg.png){#fig-hac}

## Map {.unnumbered}


## Structures Table {.unnumbered}
