# Detailed Methods {-}
## Connectivity Status Assessment Methods {-}

The connectivity status assessment for anadromous salmonids in the Margaree watershed builds on existing connectivity modelling work undertaken by the Canadian Wildlife Federation in partnership with the Atlantic Salmon Federation. The Margaree model within the NovaScotiaFishPass spatially locates known and modelled barriers to fish passage, identifies potential spawning and rearing habitat for focal species, and estimates the amount of habitat that is currently accessible to focal species within the Margaree. The model uses an adapted version of the Intrinsic Potential (IP) fish habitat modelling framework (see Sheer et al. (2009) for an overview of the IP framework). The habitat model uses two geomorphic characteristics of the stream network — channel gradient and mean annual discharge — to identify potential spawning habitat and rearing habitat for each focal species. The habitat model does not attempt to definitively map each habitat type nor estimate habitat quality, but rather identifies stream segments that have high potential to support spawning or rearing habitat for each species based on the geomorphic characteristics of the segment. For more details on the connectivity and habitat model structure and parameters, please see Mazany-Wright, N and Norris, S. M. and Lapointe, N. W. R. and Rebellato, B. (2021a). The variables and thresholds used to model potential spawning and rearing habitat for each focal species are summarized in Table 1. The quantity of modelled habitat for each species was aggregated for each habitat type and represents a linear measure of potential habitat.  

```{r, echo = FALSE, results = 'asis'}
#| label: tbl-param
#| tbl-cap: "Parameters and thresholds used to inform the Intrinsic Potential habitat model for spawning and rearing habitat for each focal species in the Margaree River watershed."
#| warning: false

library("flextable")

data <- read.csv("data/additional-key-actors.csv", check.names=FALSE)
ft <- flextable(data)
ft <- bg(ft, bg = "#008270", part = "header")
ft <- color(ft, color = "white", part = "header")
ft <- set_caption(ft)
ft |> autofit() 
```


