# Progress Reporting {-}

## Progress Reporting {-}

This WCRP was initiated in 2025 as part of a larger conservation initiative led by the Atlantic Salmon Federation, called the Wild Salmon Watersheds program, which aims to protect, restore, and maintain resilient salmon watersheds, including the Margaree. Since then, several scoping and planning meetings were held between MSA, CWF, ASF, and the Nova Scotia Salmon Association (NSSA) to gather knowledge to develop and refine the initial connectivity models. The passability status of 38 structures was assessed in the field and field results reviewed with the planning team to determine next steps for identified barriers. 


## Rehabilitated Barriers {-}

No barriers were rehabilitated through this WCRP as of 2026.  


## Annual Progress Report {-}

Since March 2025 the following actions were completed: 

- Barrier assessments were completed for 38 structures, resulting in 17 structures confirmed as barriers and 21 structures excluded as passable or non-existent, or because there was no habitat upstream.  

- The 2025 field assessments identified significant debris jams at four sites along the McDonalds Glen Brook, Mill Brook, and Gallant River. MSA staff removed the blockages to temporarily restore fish passage to 12.54 km of Atlantic Salmon habitat. Follow up assessments are needed to confirm whether fish passage was successfully restored, and in-depth habitat and passage assessments are needed to determine the next steps required to further restore connectivity.

- The connectivity model was updated based on the above actions, and outputs were incorporated into this WCRP. 
