
# Vision and Scope

## Purpose{-}

The following Watershed Connectivity Restoration Plan (WCRP) represents the culmination of a collaborative planning effort, for the Margaree watershed, the overall aim of which is to build collaborative partnerships focusing on the health of the Margaree watershed to reduce the threat of aquatic barriers to migratory fish and the livelihoods that they support. This plan was developed to identify priority strategies that the Margaree River WCRP planning team (@tbl-planteam) proposes to undertake between 2024-2035 to conserve and restore fish passage in the watershed, through crossing rehabilitation and barrier prevention strategies. 

WCRPs are long-term, actionable plans that blend local stakeholder and rightsholder knowledge with innovative geographical information systems (GIS) analyses to gain a shared understanding of where restoration efforts will have the greatest benefit for migratory fish. The planning process is inspired by the Conservation Standards (v.4.0), which is a conservation planning framework that allows planning teams to systematically identify, implement, and monitor strategies to apply the most effective solutions to high priority conservation problems. There is a rich history of fish and fish habitat conservation and restoration work in the Margaree watershed that this WCRP builds upon and aims to complement over the length of the plan. This includes work undertaken by the Margaree Salmon Association and work supported by the Nova Scotia Salmon Association (NSSA) and the Atlantic Salmon Federation (ASF). The planning team will aim to work with the Nova Scotia Department of Transportation and other local stakeholders to promote coordination, decision-making, and implementation related to this plan. 

The planning team compiled existing structure location and assessment data, habitat data, and previously identified priorities in the watershed, and combined this with local knowledge to create a strategic watershed-scale plan to improve freshwater connectivity. The Margaree River WCRP planning team applied the WCRP planning framework to define the “thematic” scope of freshwater connectivity and refine the “geographic” scope to identify the portions of the watershed where connectivity restoration efforts will take place. Additionally, the team selected focal species, assessed the current key habitat connectivity status of the watershed, defined concrete goals for gains in connectivity, undertook an iterative structure-ranking process to identify a list of priority barriers for rehabilitation to achieve those goals (@tbl-priority). Although the current version of this plan is based on the best-available information at the time of publishing, WCRPs are intended to be “living plans” that are updated regularly as new information becomes available, or if local priorities and contexts change. As such, this document should be interpreted as a current “snapshot” in time, and future iterations of this WCRP will build upon the results presented in this plan to continuously improve the practice of aquatic barrier rehabilitation for migratory fishes in the Margaree watershed. For more information on how WCRPs are developed, see Mazany-Wright et al. (2021b). 

## Vision {-}

Healthy, well-connected stream networks within the Margaree watershed support thriving populations of migratory fish. Both residents and visitors to the watershed work together to mitigate the negative effects of aquatic barriers, improving the resiliency of the stream network for the benefit and appreciation of all. The MSA has been working on fish passage barriers in smaller streams on the Margaree for many years, by removing beaver dams and clearing up blocked culverts. With this WCRP and in collaboration with ASF, CWF, and NSSA, MSA can start making data driven decisions on where to improve fish passage resulting in meaningful improvements for fish passage in the Margaree watershed. 

## Scope {-}

The geographic scope of this WCRP was further refined by identifying naturally accessible waterbodies, which are defined as streams, lakes, or reservoirs that focal species would access in the absence of anthropogenic barriers.  Naturally accessible waterbodies were spatially delineated for each species using stream characteristics that define the upper limit of their movement based on their swimming abilities (@tbl-species).  The spatial extent of the naturally accessible waterbodies layer was then refined based on existing fish observation data and/or redd surveys (for Atlantic salmon).  These maps were explored by the planning team to incorporate additional local knowledge, ensure accuracy, and finalize the criteria used to define naturally accessible waterbodies, which are shown for Atlantic salmon (@fig-geoscope).  The new geographic scope formed the foundation for all subsequent analyses and planning steps, including mapping and modelling key habitat, quantifying the current connectivity status, goal setting, and action planning {@Mazany-Wright2021-hs}

CHANGE TABLE
```{r targspec, echo = FALSE, results = 'asis'}
#| label: tbl-targspec
#| tbl-cap: "Focal fish species in the Horsefly River watershed. The Secwepemctsín and Western common and scientific species names are provided."
#| warning: false

library("flextable")

data <- read.csv("data/species_names.csv", check.names=FALSE)
ft <- flextable(data)
ft <- bg(ft, bg = "#008270", part = "header")
ft <- color(ft, color = "white", part = "header")
ft <- set_caption(ft)
#ft <- autofit()
ft |> autofit() 
```


## Focal species {-}

Focal species represent the ecologically and culturally important species for which habitat connectivity is being conserved or restored in the watershed. In the Margaree watershed, the planning team selected Atlantic salmon as a primary focus with interest in incorporating American eel in future work. The selection of these focal species was driven primarily by the focal species of the primary funds supporting this planning work , the rich angling history of the Margaree, and the current threats to Atlantic salmon in the region. 

### Atlantic Salmon {-}

Atlantic salmon are anadromous fishes, meaning mature adults spawn in freshwater and juveniles rear in freshwater before undergoing a process called smoltification where they migrate out to the ocean for 1-3+ years before returning to the freshwater to repeat this process.  Due to this migratory process, salmon require unimpeded access between the ocean and freshwater habitats to complete their life cycle.  

Atlantic salmon spawn in the pool-riffle transition zones of the main stem and larger tributaries of a river {cite}deGaudemar2000; Finstad2010.  Within these stretches, they seek out the tails of pools, where substrate size allows for females to excavate a space to deposit the eggs to incubate below gravel beds. Fast flowing, well oxygenated water with minimal fine sediments helps to maximize successful embryo development.  Atlantic salmon juveniles (fry and parr) rear in habitat that is deeper and slower, to facilitate their weaker swimming and predation capabilities.  Water depth, velocity, and substrate size tend to increase with parr as they increase in size and age.  Shelter, in the form of large rocks, boulders, or overhead cover provide crucial refuge for overwintering habitat.  Channel gradients most typically associated with these preferred spawning and rearing habitats range from 0.12 to 25%; with highest concentrations below 3% {cite}Amiro1993. 

### American Eel {-}

American eel are catadromous species, meaning they spawn in the Sargasso Sea and drift with the ocean currents towards the continental shelf as glass eels.  Elvers then continue migrating towards freshwater tributaries to feed and mature, although some populations have been known to stay in the estuaries and bays or move between freshwater and estuary habitat over their life cycle.  Their ability to tolerate a wide variety of salinities and temperature thresholds allows them to occupy a variety of habitat types. 

ADD SPECIES TABLE

## Structure Types {-}

Table 5 highlights structure types threatening anadromous salmonids in the watershed. The results of this assessment were used to inform the subsequent planning steps; and identify knowledge gaps where there are limited spatial data to inform the assessment for a specific structure type. 


MODIFY TABLE
```{python barriertype, echo=FALSE}
#| label: tbl-barriertype
#| tbl-cap: "Structure Types in the Horsefly River watershed and structure rating assessment results. For each structure type listed, Extent refers to the proportion of anadromous salmonid habitat that is being blocked by that structure type, Severity is the proportion of structures for each structure type that are known to block passage for focal species based on field assessments, and Irreversibility is the degree to which the effects of a structure type can be reversed and connectivity restored. The amount of habitat blocked used in this exercise is a representation of total amount of combined spawning and rearing habitat."
#| warning: false
#| echo: false



#condition
def condition(pct):
    rating = ""
    if pct < 30 : rating = "Low"
    elif (pct >= 30) and (pct < 71) : rating = "Medium"
    elif (pct >= 71) and (pct < 90) : rating = "High"
    else : rating = "Very High"
    return rating

#rating classifier
def rating(threat, barrier):
    if threat == "extent":
        if barrier == "DAM":
            pct = api.barrier_extent(barrier)[1]
            rating = condition(pct)
        elif barrier == "ROAD":
            pct = api.barrier_extent('ROAD, RESOURCE/OTHER')[1] + api.barrier_extent('ROAD, DEMOGRAPHIC')[1]
            rating = condition(pct)
    elif threat == "severity":
        if barrier == "DAM":
            pct = api.barrier_severity(barrier)[2]
            rating = condition(pct)
        elif barrier == "ROAD":
            pct = api.barrier_severity('ROAD, RESOURCE/OTHER')[2] + api.barrier_severity('ROAD, DEMOGRAPHIC')[2]
            rating = condition(pct)
            
    return rating
            

        




df = pd.DataFrame({"Structure Types":["Road-Stream Crossings","Lateral Barriers","Small Dams(<3m height)","Trail-stream Crossings", "Natural Barriers"],
                   "Extent":[rating("extent", "ROAD"),"High",rating("extent", "DAM"), "Low", "Medium"],
                   "Severity":[rating("severity", "ROAD"),"Very High",rating("severity", "DAM"), "Low", "High"],
                   "Irreversibility":["Medium","High","High", "Medium", "Low"],
                   "Overall Threat Rating:":["Very High","High","Medium", "Low", "Low"]
                   }).style.set_properties(subset=["Overall Threat Rating:"], **{'font-weight': 'bold'})

def highlight(val):
    red = '#ff0000;'
    yellow = '#ffff00;'
    lgreen = '#92d050;'
    dgreen = '#03853e;'

    if val=="Very High": color = red
    elif val=="High": color = yellow
    elif val=="Medium": color = lgreen
    elif val =="Low": color = dgreen
    else: color = 'white'
    return 'background-color: %s' % color

#df = df.style.set_properties(subset=["Overall Threat Rating"], **{'font-weight': 'bold'})

data = df.applymap(highlight).hide()

data.set_table_styles(
   [{
       'selector': 'th',
       'props': [('background-color', '#008270'),('text-align', 'left')]
   }])

```

### Road-stream Crossings {-}

Road-stream crossings are the most abundant structure type in the watershed, with `r sum_road` assessed and modelled crossings located on waterbodies with upstream modelled habitat. Demographic road crossings (highways, municipal, and paved roads) block `r demo_km` km of habitat (~`r demo_pct`% of the total blocked habitat), with `r demo_sev`% of assessed crossings having been identified as barriers to fish passage. Resource roads block `r resource_km` km of habitat (~`r resource_pct`%), with `r resource_sev`% of assessed crossings having been identified as barriers. The planning team felt that the data were underestimating the severity of road-stream crossing structures in the watershed, and therefore decided to update the rating from High to Very High. The planning team also felt that an irreversibility rating of Medium was appropriate due to the technical complexity and resources required to rehabilitate road-stream crossings.

### Lateral Barriers{-}

There are numerous types of lateral barriers that potentially occur in the watershed, including dykes, berms, and linear development (i.e., road and rail lines), all of which can restrict the ability of anadromous salmon to move into floodplains, riparian wetlands, and other off-channel habitats. No comprehensive lateral barrier data exists within the watershed, so threat ratings were based on qualitative local knowledge. Lateral barriers are not thought to be as prevalent as road- or rail-stream crossings but are likely very severe where they do exist. Significant lateral barriers are known to occur along the mainstem of the Horsefly River, which disconnect the mainstem river from historic floodplain and off-channel habitat. Overall, the planning team decided that a High threat rating adequately captured the effect that lateral barriers are having on connectivity in the watershed. Work to begin quantifying and mapping lateral habitat commenced in 2022, as described in the Operational Plan (@tbl-opplan) under Strategy 2: Lateral barrier rehabilitation.  

### Small Dams (<3 m height) {-}

Initially, `r num_dam` mapped small dams were identified in the watershed that had upstream modelled spawning or rearing habitat for key species. Field assessments were conducted in 2021 and 2022, and 5 of the mapped dams were identified as presenting no barrier to fish passage because they did not exist, were off channel, or had no suitable key habitat upstream (see @tbl-excluded_structures). The remaining dam, at the outlet of McKinley Lake is equipped with a fishway that provides passage for salmon. The effectiveness of the fishway on the McKinley Lake dam is unknown, and further study to assess fish passage efficiency is recommended (see @tbl-S3).

### Trail-stream Crossings{-}

There is very little spatial data available on trail-stream crossings in the watershed, so the planning team was unable to quantify the true Extent and Severity of this structure type. However, the planning team felt that trail-stream crossings are not prevalent within the watershed and that, where they do exist, they do not significantly restrict passage for anadromous salmon. As most crossings will be fords or similar structures, rehabilitation may not be required, or rehabilitation costs associated with these structures would be quite low. Overall, the planning team felt that the threat rating for trail-stream crossings was likely Low; however, the lack of ground-truthed evidence to support this rating was identified as a knowledge gap within this plan. 

### Natural Barriers {-}

Natural barriers to fish passage can include debris flows, log jams, and sediment deposits, but natural features that have always restricted fish passage (e.g., waterfalls) are not considered under this barrier type. Natural barriers are difficult to include in a spatial prioritization framework due to their transient nature. The planning team identified known natural barriers that occur throughout the watershed, such as beaver dams and log jams. Generally, these natural barriers are only severe impediments to fish passage during low-flow years, but reduced baseflows have become more common in recent years. Based on this, the planning team felt that natural barriers will be severe most years where they exist, but are mostly reversible, resulting in an overall threat rating of Low.
