# Work Planning

## Workplan Table {-}

## Operational Plan {-}

The 2026 operational plan for the Margaree River Watershed will be created in the spring of 2026 to identify potential leads, potential participants, and estimated cost for the implementation of each action to take place in the Margaree watershed. Individuals and groups who are identified as potential participants will be contacted and engaged to plan who will lead and assist throughout the execution of this WCRP. Any organizations or individuals who express interest in participating will be listed in the “Lead” or “Potential Participants” column of the created operational plan to provide clarity on task roles and responsibilities. A roadmap for future coordination and engagement will be drafted in order to support activities described in the WCRP. 

```{python echo=FALSE}
#| label: tbl-S1
#| tbl-cap: "Strategy 1"
#| warning: false
#| echo: false

import numpy as np
from IPython.display import display
import pandas as pd

 
def fix_table(val):
    return str(val)

def highlighttab7(val):
    red = '#ff0000;'
    yellow = '#ffff00;'
    lgreen = '#92d050;'
    dgreen = '#03853e;'

    if val=="Medium" or val=="Need more information": color = yellow
    elif val=="Very high" or val=="Very effective" : color = lgreen
    elif val =="High" or val=="Effective": color = dgreen
    else: color = 'white'
    return 'background-color: %s' % color

```

```{python opplan, echo=FALSE}
#| label: tbl-opplan
#| tbl-cap: "SAMPLE Operational plan to support the implementation of strategies and actions to improve connectivity for target species in watershed."
#| warning: false
#| echo: false

from IPython.display import display
import pandas as pd
import numpy as np


def df_operation(val):
    return "background-color: black; color: white"


data = pd.read_csv('data/operational-plan.csv', index_col=False)

data = data.replace(np.nan, '', regex=True)

rows = pd.IndexSlice[[], :]

data = data.style.applymap(df_operation, subset=rows).hide().set_properties(**{'text-align': 'left'})
data.set_table_styles(
   [{
       'selector': 'th',
       'props': [('background-color', '#008270'),('text-align', 'left')]
   }])

```

```{r fund, echo = FALSE, results = 'asis'}
#| label: tbl-fund
#| tbl-cap: "Potential funding sources for plan implementation in <watershed>. The Canadian Wildlife Federation and the planning team can coordinate proposal submission through these sources."
#| warning: false

library("flextable")

```

